//
//  GLGResponseCodes.m
//  TwIRCk
//
//  Created by Tim Jarratt on 7/23/13.
//  Copyright (c) 2013 General Linear Group. All rights reserved.
//

#import "GLGResponseCodes.h"

@implementation GLGResponseCodes

- (id) init {
    if (self = [super init]) {
        codes = [[NSDictionary alloc] initWithObjects:@[
                 [[GLGReplyMessage alloc] initWithName:@"rpl_myinfo"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_isupport"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_tracelink"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_traceconnecting"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_tracehandshake"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_traceunknown"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_traceoperator"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_traceuser"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_traceserver"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_tracenewtype"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statslinkinfo"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statscommands"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statscline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statsnline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statsiline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statskline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statsyline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofstats"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_umodeis"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statslline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statsuptime"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statsoline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statshline"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_statsconn"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_luserclient"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_luserop"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_luserunknown"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_luserchannels"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_luserme"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_adminme"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_adminloc1"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_adminloc2"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_adminemail"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_tracelog"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_localusers"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_globalusers"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_none"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_away"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_userhost"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_ison"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_unaway"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_noaway"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_whoisuser"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_whoisserver"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_whoisoperator"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_whowasuser"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofwho"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_whoisidle"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofwhois"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_whoischannels"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_liststart"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_list"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_listend"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_channelmodeis"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_notopic"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_topic"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_inviting"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_summoning"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_version"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_whoreply"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_namreply"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_links"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endoflinks"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofnames"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_banlist"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofbanlist"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofwhowas"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_info"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_motd"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofinfo"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_motdstart"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofmotd"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_youreoper"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_rehashing"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_time"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_usersstart"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_users"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_endofusers"],
                 [[GLGReplyMessage alloc] initWithName:@"rpl_nousers"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nosuchnick"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nosuchserver"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nosuchchannel"],
                 [[GLGErrorMessage alloc] initWithName:@"err_cannotsendtochan"],
                 [[GLGErrorMessage alloc] initWithName:@"err_toomanychannels"],
                 [[GLGErrorMessage alloc] initWithName:@"err_wasnosuchnick"],
                 [[GLGErrorMessage alloc] initWithName:@"err_toomanytargets"],
                 [[GLGErrorMessage alloc] initWithName:@"err_noorigin"],
                 [[GLGErrorMessage alloc] initWithName:@"err_norecipient"],
                 [[GLGErrorMessage alloc] initWithName:@"err_notexttosend"],
                 [[GLGErrorMessage alloc] initWithName:@"err_notoplevel"],
                 [[GLGErrorMessage alloc] initWithName:@"err_wildtoplevel"],
                 [[GLGErrorMessage alloc] initWithName:@"err_unknowncommand"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nomotd"],
                 [[GLGErrorMessage alloc] initWithName:@"err_noadmininfo"],
                 [[GLGErrorMessage alloc] initWithName:@"err_fileerror"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nonicknamegiven"],
                 [[GLGErrorMessage alloc] initWithName:@"err_erroneusnickname"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nicknameinuse"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nickcollision"],
                 [[GLGErrorMessage alloc] initWithName:@"err_usernotinchannel"],
                 [[GLGErrorMessage alloc] initWithName:@"err_notonchannel"],
                 [[GLGErrorMessage alloc] initWithName:@"err_useronchannel"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nologin"],
                 [[GLGErrorMessage alloc] initWithName:@"err_summondisabled"],
                 [[GLGErrorMessage alloc] initWithName:@"err_usersdisabled"],
                 [[GLGErrorMessage alloc] initWithName:@"err_notregistered"],
                 [[GLGErrorMessage alloc] initWithName:@"err_needmoreparams"],
                 [[GLGErrorMessage alloc] initWithName:@"err_alreadyregistered"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nopermforhost"],
                 [[GLGErrorMessage alloc] initWithName:@"err_passwdmismatch"],
                 [[GLGErrorMessage alloc] initWithName:@"err_yourebannedcreep"],
                 [[GLGErrorMessage alloc] initWithName:@"err_keyset"],
                 [[GLGErrorMessage alloc] initWithName:@"err_channelisfull"],
                 [[GLGErrorMessage alloc] initWithName:@"err_unknownmode"],
                 [[GLGErrorMessage alloc] initWithName:@"err_inviteonlychan"],
                 [[GLGErrorMessage alloc] initWithName:@"err_bannedfromchan"],
                 [[GLGErrorMessage alloc] initWithName:@"err_badchannelkey"],
                 [[GLGErrorMessage alloc] initWithName:@"err_noprivileges"],
                 [[GLGErrorMessage alloc] initWithName:@"err_chanoprivsneeded"],
                 [[GLGErrorMessage alloc] initWithName:@"err_cantkillserver"],
                 [[GLGErrorMessage alloc] initWithName:@"err_nooperhost"],
                 [[GLGErrorMessage alloc] initWithName:@"err_umodeunknownflag"],
                 [[GLGErrorMessage alloc] initWithName:@"err_usersdontmatch"],
                 ]
                                              forKeys:@[
                 @004,
                 @005,
                 @200,
                 @201,
                 @202,
                 @203,
                 @204,
                 @205,
                 @206,
                 @208,
                 @211,
                 @212,
                 @213,
                 @214,
                 @215,
                 @216,
                 @218,
                 @219,
                 @221,
                 @241,
                 @242,
                 @243,
                 @244,
                 @250,
                 @251,
                 @252,
                 @253,
                 @254,
                 @255,
                 @256,
                 @257,
                 @258,
                 @259,
                 @261,
                 @265,
                 @266,
                 @300,
                 @301,
                 @302,
                 @303,
                 @305,
                 @306,
                 @311,
                 @312,
                 @313,
                 @314,
                 @315,
                 @317,
                 @318,
                 @319,
                 @321,
                 @322,
                 @323,
                 @324,
                 @331,
                 @332,
                 @341,
                 @342,
                 @351,
                 @352,
                 @353,
                 @364,
                 @365,
                 @366,
                 @367,
                 @368,
                 @369,
                 @371,
                 @372,
                 @374,
                 @375,
                 @376,
                 @381,
                 @382,
                 @391,
                 @392,
                 @393,
                 @394,
                 @395,
                 @401,
                 @402,
                 @403,
                 @404,
                 @405,
                 @406,
                 @407,
                 @409,
                 @411,
                 @412,
                 @413,
                 @414,
                 @421,
                 @422,
                 @423,
                 @424,
                 @431,
                 @432,
                 @433,
                 @436,
                 @441,
                 @442,
                 @443,
                 @444,
                 @445,
                 @446,
                 @451,
                 @461,
                 @462,
                 @463,
                 @464,
                 @465,
                 @467,
                 @471,
                 @472,
                 @473,
                 @474,
                 @475,
                 @481,
                 @482,
                 @483,
                 @491,
                 @501,
                 @502,
                 ]];
    }

    return self;
}

- (GLGReplyMessage *) replyForCode:(NSNumber *) code {
    return [codes objectForKey:code];
}

@end
