require 'pathname'

module Specs
  SPECS_TARGET_NAME = "Specs"
  CONFIGURATION = "Release"

  PROJECT_ROOT = Pathname.new(File.dirname(__FILE__)).parent.to_s
  BUILD_DIR = File.join(PROJECT_ROOT, "build")

  FileUtils.mkdir_p(File.join(BUILD_DIR, CONFIGURATION))

  class << self
    def in_project_dir
      original_dir = Dir.pwd
      Dir.chdir(PROJECT_ROOT)

      yield

      ensure
      Dir.chdir(original_dir)
    end

    def build_dir
      File.join(BUILD_DIR, CONFIGURATION)
    end

    def system_or_exit(cmd, stdout = nil)
      puts "Executing #{cmd}"
      cmd += " >#{stdout}" if stdout
      system(cmd) or raise "******** Build failed ********"
    end

    def with_env_vars(env_vars)
      old_values = {}
      env_vars.each do |key,new_value|
        old_values[key] = ENV[key]
        ENV[key] = new_value
      end

      yield

      env_vars.each_key do |key|
        ENV[key] = old_values[key]
      end
    end

    def output_file(target)
      output_dir = if ENV['IS_CI_BOX']
        ENV['CC_BUILD_ARTIFACTS']
      else
        Dir.mkdir(BUILD_DIR) unless File.exists?(BUILD_DIR)
        BUILD_DIR
      end

      output_file = File.join(output_dir, "#{target}.output")
      puts "Output: #{output_file}"
      output_file
    end
  end
end

desc "Clean build directory"
task :clean_Specs do
  Specs.system_or_exit "rm -rf #{Specs::BUILD_DIR}/*", Specs.output_file("clean")
end

desc "Build Specs Specs"
task :build_Specs do
  Specs.system_or_exit(%Q[pushd #{Specs::PROJECT_ROOT} ; xcodebuild -target #{Specs::SPECS_TARGET_NAME} -configuration #{Specs::CONFIGURATION} build SYMROOT=#{Specs::BUILD_DIR} ; popd ], Specs.output_file("Specs"))
end

desc "Run Specs Specs"
task :Specs => :build_Specs do
  Specs.with_env_vars("DYLD_FRAMEWORK_PATH" => Specs.build_dir, "CEDAR_REPORTER_CLASS" => "CDRColorizedReporter") do
    Specs.system_or_exit(File.join(Specs.build_dir, Specs::SPECS_TARGET_NAME))
  end
end

